name: CI Pipeline Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js v20.17.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Verificar a instalação do Node.js
        run: node -v

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npx jest
