name: CI Pipeline Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Baixar e Instalar Node.js v20.17.0 Manualmente
        run: |
          Invoke-WebRequest -Uri "https://nodejs.org/dist/v20.17.0/node-v20.17.0-x64.msi" -OutFile "node.msi"
          Start-Process "node.msi" -ArgumentList "/quiet" -NoNewWindow -Wait
          echo "Verificando instalação do Node.js"
          if (-Not (Test-Path "C:\Program Files\nodejs\node.exe")) { exit 1 }

      - name: Adicionar Node.js ao PATH
        run: |
          echo "C:\Program Files\nodejs" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      - name: Verificar a instalação do Node.js
        run: node -v

      - name: Instalar dependências
        run: npm install

      - name: Instalar Jest manualmente
        run: npm install --save-dev jest

      - name: Rodar testes com Jest
        run: npx jest
